version: "3.8"
services:
  redis:
    container_name: clw-parser
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - cbh_thc_network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  redis:
    driver: local

networks:
  cbh_thc_network:
    driver: bridge
